### ISSUE TITLE
Mapa_Mental

### ISSUE THREAD

**Issue by Fidel20-01** [SistemasTecTlaxiaco/actividad-4-mapa-mental-Fidel20-01#2]
![24620171](https://github.com/user-attachments/assets/e3d74cda-b425-49ce-94c3-2bc3c3668122)
[24620171.pdf](https://github.com/user-attachments/files/17119263/24620171.pdf)

**Comment by josealfredo79** [comment]
Calificacion 20 Bien hecho y revisado..
